# Generated by Django 3.2.15 on 2022-08-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220823_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInCart',
        ),
    ]
