# Generated by Django 3.2.15 on 2022-08-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_order_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='users',
            new_name='user',
        ),
    ]
